input_folder: ""
geojson_folder: "/Users/lu/Desktop/test_correct"
font_file: "/System/Library/Fonts/PingFang.ttc"

figsize_w: 16
figsize_h: 16

fontsize_min: 4
fontsize_max: 12
fontsize_init: 7

languages:
  - Chinese
  - English
  - Russian

score_colors:
  none: [0, 0, 0]  # Black 
  red: [1, 0, 0]  # Red
  orange: [1, 0.5, 0]  # Orange
  green: [0, 0.9, 0.1]  # Green
  dark_green: [0, 0.5, 0]  # Dark green
